version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm install -g yarn
      - export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
      - yarn install
  build:
    commands:
      - echo Building the application...
      - npm run build
  post_build:
    commands:
      - echo Deploying to S3...
      - aws s3 sync build/ s3://auto-garage-ui-bucket --delete

artifacts:
  files:
    - '**/*'
  base-directory: build