version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo Setting max listeners to 20
      - node -e "require('events').defaultMaxListeners = 20;"
      - echo Installing dependencies with limited sockets...
      - npm install --maxsockets=5
  build:
    commands:
      - echo Building the application...
      - npm run build
  post_build:
    commands:
      - echo Deploying to S3...
      - aws s3 sync build/ s3://auto-garage-ui-bucket --delete

artifacts:
  files:
    - '**/*'
  base-directory: build